/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import Modelo.TabelaDTO;
import Modelo.UsuarioDAO;
import Modelo.UsuarioDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author QUARTZO
 */
public class FormUsuariosGUI extends javax.swing.JFrame {

    UsuarioDTO userdto = new UsuarioDTO();
    UsuarioDAO userdao = new UsuarioDAO();
    Conexao conn = new Conexao();
    String tabusers = "cadusuarios";
    int cont = 0;
    
    
    public FormUsuariosGUI() {
        initComponents();
        
        preencherTabela("SELECT * FROM " + tabusers + " ORDER BY nome_user");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo_caduser = new javax.swing.JPanel();
        f_cadusernome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTipoAcesso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_cadUsersalvar = new javax.swing.JButton();
        btn_cadUseredit = new javax.swing.JButton();
        btn_cadUserexcluir = new javax.swing.JButton();
        btn_cadUsercancel = new javax.swing.JButton();
        btn_cadUsernovo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        f_cadusercod = new javax.swing.JTextField();
        btn_cadUserbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_caduser = new javax.swing.JTable();
        f_cadusersenha2 = new javax.swing.JPasswordField();
        f_cadusersenha = new javax.swing.JPasswordField();
        f_caduseruser = new javax.swing.JTextField();
        f_caduseremail = new javax.swing.JTextField();
        f_caduserrg = new javax.swing.JTextField();
        f_caduserbuscar = new javax.swing.JTextField();
        txt_cadusuarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        fundo_caduser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        f_cadusernome.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Usuário:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tipo:");

        jTipoAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Médico", "Recepcionista", " " }));
        jTipoAcesso.setEnabled(false);
        jTipoAcesso.setRequestFocusEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("R.G:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Senha:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Conf. Senha:");

        btn_cadUsersalvar.setText("SALVAR");
        btn_cadUsersalvar.setEnabled(false);
        btn_cadUsersalvar.setRequestFocusEnabled(false);
        btn_cadUsersalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadUsersalvarActionPerformed(evt);
            }
        });

        btn_cadUseredit.setText("EDITAR");
        btn_cadUseredit.setEnabled(false);
        btn_cadUseredit.setRequestFocusEnabled(false);
        btn_cadUseredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadUsereditActionPerformed(evt);
            }
        });

        btn_cadUserexcluir.setText("EXCLUIR");
        btn_cadUserexcluir.setEnabled(false);
        btn_cadUserexcluir.setRequestFocusEnabled(false);
        btn_cadUserexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadUserexcluirActionPerformed(evt);
            }
        });

        btn_cadUsercancel.setText("CANCELAR");
        btn_cadUsercancel.setEnabled(false);
        btn_cadUsercancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadUsercancelActionPerformed(evt);
            }
        });

        btn_cadUsernovo.setText("NOVO");
        btn_cadUsernovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadUsernovoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ID:");

        f_cadusercod.setEnabled(false);
        f_cadusercod.setRequestFocusEnabled(false);

        btn_cadUserbuscar.setText("Buscar");
        btn_cadUserbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadUserbuscarActionPerformed(evt);
            }
        });

        table_caduser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_caduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_caduserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_caduser);

        f_cadusersenha2.setEnabled(false);

        f_cadusersenha.setEnabled(false);

        f_caduseruser.setEnabled(false);

        f_caduseremail.setEnabled(false);

        f_caduserrg.setEnabled(false);

        javax.swing.GroupLayout fundo_caduserLayout = new javax.swing.GroupLayout(fundo_caduser);
        fundo_caduser.setLayout(fundo_caduserLayout);
        fundo_caduserLayout.setHorizontalGroup(
            fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo_caduserLayout.createSequentialGroup()
                .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo_caduserLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(f_cadusersenha, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fundo_caduserLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(f_cadusersenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cadUseredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cadUserexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cadUsercancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTipoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(f_cadusercod, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(f_caduserbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn_cadUserbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo_caduserLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo_caduserLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(19, 19, 19)
                                .addComponent(f_cadusernome, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3)
                                .addGap(4, 4, 4)
                                .addComponent(f_caduseruser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btn_cadUsernovo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo_caduserLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(f_caduseremail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)
                                .addGap(4, 4, 4)
                                .addComponent(f_caduserrg, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btn_cadUsersalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39))
        );
        fundo_caduserLayout.setVerticalGroup(
            fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo_caduserLayout.createSequentialGroup()
                .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo_caduserLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2))
                            .addComponent(f_cadusernome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fundo_caduserLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3))
                            .addGroup(fundo_caduserLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(f_caduseruser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_cadUsernovo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(f_caduseremail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6))
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(f_caduserrg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_cadUsersalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(f_cadusersenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo_caduserLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8))
                            .addComponent(f_cadusersenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addComponent(btn_cadUseredit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn_cadUserexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn_cadUsercancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTipoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_cadusercod, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fundo_caduserLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(fundo_caduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_caduserbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadUserbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(fundo_caduser);
        fundo_caduser.setBounds(10, 50, 770, 560);

        txt_cadusuarios.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_cadusuarios.setForeground(new java.awt.Color(0, 102, 102));
        txt_cadusuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_cadusuarios.setText("Cadastro de Usuários");
        getContentPane().add(txt_cadusuarios);
        txt_cadusuarios.setBounds(260, 10, 280, 30);

        setSize(new java.awt.Dimension(797, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadUsernovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadUsernovoActionPerformed
        cont = 1;
        f_cadusernome.setEnabled(true);
        f_caduseruser.setEnabled(true);
        f_caduseremail.setEnabled(true);
        f_caduserrg.setEnabled(true);
        f_cadusersenha.setEnabled(true);
        f_cadusersenha2.setEnabled(true);
        jTipoAcesso.setEnabled(true);
        f_caduserbuscar.setEnabled(false);
        
        f_cadusercod.setText("");
        f_cadusernome.setText("");
        f_caduseruser.setText("");
        f_caduseremail.setText("");
        f_caduserrg.setText("");
        f_cadusersenha.setText("");
        f_cadusersenha2.setText("");
        
        btn_cadUsersalvar.setEnabled(true);
        btn_cadUsercancel.setEnabled(true);
        btn_cadUserbuscar.setEnabled(false);
        btn_cadUserexcluir.setEnabled(false);
        btn_cadUseredit.setEnabled(false);
        btn_cadUsernovo.setEnabled(false);
        
        f_cadusernome.requestFocus();
        
    }//GEN-LAST:event_btn_cadUsernovoActionPerformed

    private void btn_cadUsersalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadUsersalvarActionPerformed
        if(f_cadusernome.getText().isEmpty() || f_caduseruser.getText().isEmpty() || f_caduseremail.getText().isEmpty() 
           || f_caduserrg.getText().isEmpty() || f_cadusersenha.getText().isEmpty() || f_cadusersenha2.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Preeencha todos os campos.");
            f_cadusernome.requestFocus();
            
                        
        }else{
           if(f_cadusersenha.getText().equals(f_cadusersenha2.getText())){
                if(cont == 1){
                    userdto.setUserNome(f_cadusernome.getText());
                    userdto.setUserUsuario(f_caduseruser.getText());
                    userdto.setUserEmail(f_caduseremail.getText());
                    userdto.setUserRg(Integer.parseInt(f_caduserrg.getText()));
                    userdto.setUserSenha(f_cadusersenha.getText());
                    userdto.setUserSenha2(f_cadusersenha2.getText());
                    userdto.setUserTipo((String) jTipoAcesso.getSelectedItem());

                    userdao.Salvar(userdto);
                    preencherTabela("SELECT * FROM " + tabusers + " ORDER BY nome_user");
                    f_cadusernome.setText("");
                    f_caduseruser.setText("");
                    f_caduseremail.setText("");
                    f_caduserrg.setText("");
                    f_cadusersenha.setText("");
                    f_cadusersenha2.setText("");
                    f_caduserbuscar.setText("");

                    f_cadusernome.setEnabled(false);
                    f_caduseruser.setEnabled(false);
                    f_caduseremail.setEnabled(false);
                    f_caduserrg.setEnabled(false);
                    f_cadusersenha.setEnabled(false);
                    f_cadusersenha2.setEnabled(false);
                    jTipoAcesso.setEnabled(false);
                    f_caduserbuscar.setEnabled(true);

                    btn_cadUsersalvar.setEnabled(false);
                    btn_cadUsercancel.setEnabled(false);
                    btn_cadUserbuscar.setEnabled(true);
                }
                else{
                    userdto.setUserCod(Integer.parseInt(f_cadusercod.getText()));
                    userdto.setUserNome(f_cadusernome.getText());
                    userdto.setUserUsuario(f_caduseruser.getText());
                    userdto.setUserEmail(f_caduseremail.getText());
                    userdto.setUserRg(Integer.parseInt(f_caduserrg.getText()));
                    userdto.setUserSenha(f_cadusersenha.getText());
                    userdto.setUserSenha2(f_cadusersenha2.getText());
                    userdto.setUserTipo((String) jTipoAcesso.getSelectedItem());

                    userdao.editar(userdto);
                    preencherTabela("SELECT * FROM " + tabusers + " ORDER BY nome_user");
                    f_cadusernome.setText("");
                    f_caduseruser.setText("");
                    f_caduseremail.setText("");
                    f_caduserrg.setText("");
                    f_cadusersenha.setText("");
                    f_cadusersenha2.setText("");
                    f_cadusercod.setText("");

                    f_cadusernome.setEnabled(false);
                    f_caduseruser.setEnabled(false);
                    f_caduseremail.setEnabled(false);
                    f_caduserrg.setEnabled(false);
                    f_cadusersenha.setEnabled(false);
                    f_cadusersenha2.setEnabled(false);
                    jTipoAcesso.setEnabled(false);
                    f_caduserbuscar.setEnabled(true);

                    btn_cadUsersalvar.setEnabled(false);
                    btn_cadUsercancel.setEnabled(false);
                    btn_cadUserbuscar.setEnabled(true);
                    btn_cadUseredit.setEnabled(false);
                    btn_cadUserexcluir.setEnabled(false);
                }
            }else{
               JOptionPane.showMessageDialog(null, "As senhas não são iguais. Tente novamente.");
           } 
        }      
    }//GEN-LAST:event_btn_cadUsersalvarActionPerformed

    private void btn_cadUserbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadUserbuscarActionPerformed
        userdto.setPesquisa(f_caduserbuscar.getText());
        
        UsuarioDTO userDTO = userdao.pesquisaUser(userdto);
        f_cadusercod.setText(String.valueOf(userDTO.getUserCod()));
        f_cadusernome.setText(userDTO.getUserNome());
        f_caduseruser.setText(userDTO.getUserUsuario());
        f_caduseremail.setText(userDTO.getUserEmail());
        f_caduserrg.setText(String.valueOf(userDTO.getUserRg()));
        f_cadusersenha.setText(userDTO.getUserSenha());
        f_cadusersenha2.setText(userDTO.getUserSenha2());
        jTipoAcesso.setSelectedItem(userDTO.getUserTipo());
        
        btn_cadUseredit.setEnabled(false);
        btn_cadUserexcluir.setEnabled(false);
        f_cadusernome.setText("");
        f_caduseruser.setText("");
        f_caduseremail.setText("");
        f_caduserrg.setText("");
        f_cadusersenha.setText("");
        f_cadusersenha2.setText("");
        f_cadusercod.setText("");
        
        preencherTabela("SELECT * FROM " + tabusers + " WHERE nome_user like '%" + userdto.getPesquisa()+"%'");
    }//GEN-LAST:event_btn_cadUserbuscarActionPerformed

    private void btn_cadUsereditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadUsereditActionPerformed
        cont = 2;
        f_cadusernome.setEnabled(true);
        f_caduseruser.setEnabled(true);
        f_caduseremail.setEnabled(true);
        f_caduserrg.setEnabled(true);
        f_cadusersenha.setEnabled(true);
        f_cadusersenha2.setEnabled(true);
        jTipoAcesso.setEnabled(true);
        f_caduserbuscar.setEnabled(false);
        btn_cadUserbuscar.setEnabled(false);
        btn_cadUseredit.setEnabled(false);
        btn_cadUsersalvar.setEnabled(true);
        btn_cadUserexcluir.setEnabled(false);
        btn_cadUsercancel.setEnabled(true);
        
        
    }//GEN-LAST:event_btn_cadUsereditActionPerformed

    private void btn_cadUserexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadUserexcluirActionPerformed
        int resp = 0;
        resp = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir esse registro?");
        if(resp == JOptionPane.YES_OPTION){
            userdto.setUserCod(Integer.parseInt(f_cadusercod.getText()));
            userdao.excluir(userdto);
             preencherTabela("SELECT * FROM " + tabusers + " ORDER BY nome_user");
            f_cadusernome.setEnabled(false);
            f_caduseruser.setEnabled(false);
            f_caduseremail.setEnabled(false);
            f_caduserrg.setEnabled(false);
            f_cadusersenha.setEnabled(false);
            f_cadusersenha2.setEnabled(false);
            jTipoAcesso.setEnabled(false);
            btn_cadUsersalvar.setEnabled(false);
            btn_cadUsernovo.setEnabled(true);
            btn_cadUsercancel.setEnabled(false);
            btn_cadUseredit.setEnabled(false);
            btn_cadUserexcluir.setEnabled(false);
            
            f_cadusercod.setText("");
            f_cadusernome.setText("");
            f_caduseruser.setText("");
            f_caduseremail.setText("");
            f_caduserrg.setText("");
            f_cadusersenha.setText("");
            f_cadusersenha2.setText("");
            jTipoAcesso.setSelectedItem("");
        }
    }//GEN-LAST:event_btn_cadUserexcluirActionPerformed

    private void btn_cadUsercancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadUsercancelActionPerformed
        f_cadusernome.setEnabled(!true);
        f_caduseruser.setEnabled(!true);
        f_caduseremail.setEnabled(!true);
        f_caduserrg.setEnabled(!true);
        f_cadusersenha.setEnabled(!true);
        f_cadusersenha2.setEnabled(!true);
        jTipoAcesso.setEnabled(!true);
        f_caduserbuscar.setEnabled(true);
        btn_cadUsersalvar.setEnabled(!true);
        btn_cadUsernovo.setEnabled(true);
        btn_cadUseredit.setEnabled(false);
        btn_cadUsercancel.setEnabled(false);
        btn_cadUserexcluir.setEnabled(false);
        btn_cadUserbuscar.setEnabled(true);
        
        f_cadusercod.setText("");
        f_cadusernome.setText("");
        f_caduseruser.setText("");
        f_caduseremail.setText("");
        f_caduserrg.setText("");
        f_cadusersenha.setText("");
        f_cadusersenha2.setText("");
    }//GEN-LAST:event_btn_cadUsercancelActionPerformed

    private void table_caduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_caduserMouseClicked
        String nome_user = ""+table_caduser.getValueAt(table_caduser.getSelectedRow(), 1);
        conn.conect();
        String query = "SELECT * FROM " + tabusers + " WHERE nome_user = '" + nome_user + "'";
        conn.executaSql(query);
        try {
            conn.rs.first();
            f_cadusercod.setText(String.valueOf(conn.rs.getInt("cod_user")));
            f_cadusernome.setText(conn.rs.getString("nome_user"));
            f_caduseruser.setText(conn.rs.getString("usuario_user"));
            f_caduseremail.setText(conn.rs.getString("email_user"));
            f_caduserrg.setText(String.valueOf(conn.rs.getString("rg_user")));
            f_cadusersenha.setText(conn.rs.getString("senha_user"));
            f_cadusersenha2.setText(conn.rs.getString("senha2_user"));
            jTipoAcesso.setSelectedItem(conn.rs.getString("acesso_user"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar o registro: " + ex);
        }
            btn_cadUsernovo.setEnabled(false);
            btn_cadUsersalvar.setEnabled(false);
            btn_cadUsercancel.setEnabled(true);
            btn_cadUseredit.setEnabled(true);
            btn_cadUserexcluir.setEnabled(true);
            
            f_cadusernome.setEnabled(!true);
            f_caduseruser.setEnabled(!true);
            f_caduseremail.setEnabled(!true);
            f_caduserrg.setEnabled(!true);
            f_cadusersenha.setEnabled(!true);
            f_cadusersenha2.setEnabled(!true);
            
    }//GEN-LAST:event_table_caduserMouseClicked

    public void preencherTabela(String sql){
        
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Usuário", "E-mail", "RG", "Tipo"};
        conn.conect();
        conn.executaSql(sql);
        
        try {
            conn.rs.first();
            do {                
                dados.add(new Object[]{conn.rs.getInt("cod_user"), conn.rs.getString("nome_user"), conn.rs.getString("usuario_user"),
                    conn.rs.getString("email_user"), conn.rs.getInt("rg_user"), conn.rs.getString("acesso_user")});
                                    
            } while (conn.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Insira outro nome para preencher a tabela!");
        }
        
        TabelaDTO tabdto = new TabelaDTO(dados, colunas);
                
        table_caduser.setModel(tabdto);
        table_caduser.getColumnModel().getColumn(0).setPreferredWidth(30);
        table_caduser.getColumnModel().getColumn(0).setResizable(false);
        table_caduser.getColumnModel().getColumn(1).setPreferredWidth(150);
        table_caduser.getColumnModel().getColumn(1).setResizable(false);
        table_caduser.getColumnModel().getColumn(2).setPreferredWidth(100);
        table_caduser.getColumnModel().getColumn(2).setResizable(false);
        table_caduser.getColumnModel().getColumn(3).setPreferredWidth(210);
        table_caduser.getColumnModel().getColumn(3).setResizable(false);
        table_caduser.getColumnModel().getColumn(4).setPreferredWidth(100);
        table_caduser.getColumnModel().getColumn(4).setResizable(false);
        table_caduser.getColumnModel().getColumn(5).setPreferredWidth(100);
        table_caduser.getColumnModel().getColumn(5).setResizable(false);
        
        table_caduser.getTableHeader().setReorderingAllowed(false);
        table_caduser.setAutoResizeMode(table_caduser.AUTO_RESIZE_OFF);
        table_caduser.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuariosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuariosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuariosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuariosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuariosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadUserbuscar;
    private javax.swing.JButton btn_cadUsercancel;
    private javax.swing.JButton btn_cadUseredit;
    private javax.swing.JButton btn_cadUserexcluir;
    private javax.swing.JButton btn_cadUsernovo;
    private javax.swing.JButton btn_cadUsersalvar;
    private javax.swing.JTextField f_caduserbuscar;
    private javax.swing.JTextField f_cadusercod;
    private javax.swing.JTextField f_caduseremail;
    private javax.swing.JTextField f_cadusernome;
    private javax.swing.JTextField f_caduserrg;
    private javax.swing.JPasswordField f_cadusersenha;
    private javax.swing.JPasswordField f_cadusersenha2;
    private javax.swing.JTextField f_caduseruser;
    private javax.swing.JPanel fundo_caduser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jTipoAcesso;
    private javax.swing.JTable table_caduser;
    private javax.swing.JLabel txt_cadusuarios;
    // End of variables declaration//GEN-END:variables
}
