/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import Modelo.MedicoDAO;
import Modelo.MedicoDTO;
import Modelo.TabelaDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author QUARTZO
 */
public class FormMedicoGUI extends javax.swing.JFrame {

    String banco = "projetoclinica";
    String tabmed = "cadmedicos";
    int cont = 0;
    MedicoDTO meddto = new MedicoDTO();
    MedicoDAO meddao = new MedicoDAO();
    Conexao conn = new Conexao();
        
    public FormMedicoGUI() {
        initComponents();
        
        preencherTabela("SELECT * FROM cadmedicos ORDER BY nome_med");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo_cadmed = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        f_cadmednasc = new javax.swing.JTextField();
        f_cadmednome = new javax.swing.JTextField();
        f_cadmedcrm = new javax.swing.JTextField();
        f_cadmedend = new javax.swing.JTextField();
        f_cadmedemail = new javax.swing.JTextField();
        f_cadmedtel = new javax.swing.JTextField();
        jEspecializacao = new javax.swing.JComboBox<>();
        btn_cadnovo = new javax.swing.JButton();
        btn_cadsalvar = new javax.swing.JButton();
        btn_cadedit = new javax.swing.JButton();
        btn_cadexcluir = new javax.swing.JButton();
        btn_cadcancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cadmed = new javax.swing.JTable();
        f_cadmedpesquisa = new javax.swing.JTextField();
        btn_cadpesquisa = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        f_cadmedcod = new javax.swing.JTextField();
        txt_cadmedicos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        fundo_cadmed.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CRM:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Especialização:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Data de nascimento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Endereço:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("E-mail:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Telefone:");

        f_cadmednasc.setEnabled(false);
        f_cadmednasc.setRequestFocusEnabled(false);

        f_cadmednome.setEnabled(false);
        f_cadmednome.setRequestFocusEnabled(false);

        f_cadmedcrm.setEnabled(false);
        f_cadmedcrm.setRequestFocusEnabled(false);

        f_cadmedend.setEnabled(false);
        f_cadmedend.setRequestFocusEnabled(false);

        f_cadmedemail.setEnabled(false);
        f_cadmedemail.setRequestFocusEnabled(false);

        f_cadmedtel.setEnabled(false);
        f_cadmedtel.setRequestFocusEnabled(false);

        jEspecializacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cirurgião", "Cardiologista", " " }));
        jEspecializacao.setEnabled(false);
        jEspecializacao.setRequestFocusEnabled(false);

        btn_cadnovo.setText("NOVO");
        btn_cadnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadnovoActionPerformed(evt);
            }
        });

        btn_cadsalvar.setText("SALVAR");
        btn_cadsalvar.setEnabled(false);
        btn_cadsalvar.setRequestFocusEnabled(false);
        btn_cadsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadsalvarActionPerformed(evt);
            }
        });

        btn_cadedit.setText("EDITAR");
        btn_cadedit.setEnabled(false);
        btn_cadedit.setRequestFocusEnabled(false);
        btn_cadedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadeditActionPerformed(evt);
            }
        });

        btn_cadexcluir.setText("EXCLUIR");
        btn_cadexcluir.setEnabled(false);
        btn_cadexcluir.setRequestFocusEnabled(false);
        btn_cadexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadexcluirActionPerformed(evt);
            }
        });

        btn_cadcancel.setText("CANCELAR");
        btn_cadcancel.setEnabled(false);
        btn_cadcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadcancelActionPerformed(evt);
            }
        });

        table_cadmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_cadmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_cadmedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_cadmed);

        f_cadmedpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_cadmedpesquisaActionPerformed(evt);
            }
        });

        btn_cadpesquisa.setText("Pesquisar");
        btn_cadpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadpesquisaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ID:");

        f_cadmedcod.setDragEnabled(true);
        f_cadmedcod.setEnabled(false);
        f_cadmedcod.setRequestFocusEnabled(false);

        javax.swing.GroupLayout fundo_cadmedLayout = new javax.swing.GroupLayout(fundo_cadmed);
        fundo_cadmed.setLayout(fundo_cadmedLayout);
        fundo_cadmedLayout.setHorizontalGroup(
            fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo_cadmedLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fundo_cadmedLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(f_cadmedcrm, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_cadmedend))
                    .addGroup(fundo_cadmedLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_cadmednome, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_cadmednasc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundo_cadmedLayout.createSequentialGroup()
                        .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_cadsalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cadedit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cadexcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cadcancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cadnovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundo_cadmedLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(fundo_cadmedLayout.createSequentialGroup()
                                        .addComponent(jEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(f_cadmedcod, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo_cadmedLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(f_cadmedpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cadpesquisa)
                                .addGap(84, 84, 84))))
                    .addGroup(fundo_cadmedLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_cadmedemail, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_cadmedtel)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        fundo_cadmedLayout.setVerticalGroup(
            fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo_cadmedLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(f_cadmednasc, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(f_cadmednome, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(f_cadmedcrm, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(f_cadmedend, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(f_cadmedemail, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(f_cadmedtel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(f_cadmedcod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_cadnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(fundo_cadmedLayout.createSequentialGroup()
                            .addComponent(f_cadmedpesquisa)
                            .addGap(6, 6, 6)))
                    .addComponent(btn_cadpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundo_cadmedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fundo_cadmedLayout.createSequentialGroup()
                        .addComponent(btn_cadsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cadedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cadexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cadcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(254, 254, 254))
        );

        getContentPane().add(fundo_cadmed);
        fundo_cadmed.setBounds(20, 60, 770, 410);

        txt_cadmedicos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_cadmedicos.setForeground(new java.awt.Color(0, 102, 102));
        txt_cadmedicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_cadmedicos.setText("Cadastro de Médicos");
        getContentPane().add(txt_cadmedicos);
        txt_cadmedicos.setBounds(260, 10, 280, 30);

        setSize(new java.awt.Dimension(797, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadsalvarActionPerformed
        if(f_cadmednome.getText().isEmpty() || f_cadmednasc.getText().isEmpty() || f_cadmedcrm.getText().isEmpty() 
           || f_cadmedend.getText().isEmpty() || f_cadmedemail.getText().isEmpty() || f_cadmedtel.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Preeencha todos os campos.");
            f_cadmednome.requestFocus();
            
                        
        }else{
            if(cont == 1){
            meddto.setNome(f_cadmednome.getText());
            meddto.setNasc(Integer.parseInt(f_cadmednasc.getText()));
            meddto.setCrm(Integer.parseInt(f_cadmedcrm.getText()));
            meddto.setEndereco(f_cadmedend.getText());
            meddto.setEmail(f_cadmedemail.getText());
            meddto.setTelefone(f_cadmedtel.getText());
            meddto.setEspecializacao((String) jEspecializacao.getSelectedItem());

            meddao.Salvar(meddto);

            f_cadmednome.setText("");
            f_cadmednasc.setText("");
            f_cadmedcrm.setText("");
            f_cadmedend.setText("");
            f_cadmedemail.setText("");
            f_cadmedtel.setText("");

            f_cadmednome.setEnabled(false);
            f_cadmednasc.setEnabled(false);
            f_cadmedcrm.setEnabled(false);
            f_cadmedend.setEnabled(false);
            f_cadmedemail.setEnabled(false);
            f_cadmedtel.setEnabled(false);
            jEspecializacao.setEnabled(false);
            btn_cadsalvar.setEnabled(false);
            btn_cadcancel.setEnabled(false);
            preencherTabela("SELECT * FROM cadmedicos ORDER BY nome_med");
            }
            else{
                meddto.setCodigo(Integer.parseInt(f_cadmedcod.getText()));
                meddto.setNome(f_cadmednome.getText());
                meddto.setNasc(Integer.parseInt(f_cadmednasc.getText()));
                meddto.setCrm(Integer.parseInt(f_cadmedcrm.getText()));
                meddto.setEndereco(f_cadmedend.getText());
                meddto.setEmail(f_cadmedemail.getText());
                meddto.setTelefone(f_cadmedtel.getText());
                meddto.setEspecializacao((String) jEspecializacao.getSelectedItem());
            
                meddao.editar(meddto);

                f_cadmednome.setEnabled(false);
                f_cadmednasc.setEnabled(false);
                f_cadmedcrm.setEnabled(false);
                f_cadmedend.setEnabled(false);
                f_cadmedemail.setEnabled(false);
                f_cadmedtel.setEnabled(false);
                jEspecializacao.setEnabled(false);
                btn_cadsalvar.setEnabled(false);
                btn_cadnovo.setEnabled(true);
                btn_cadcancel.setEnabled(false);

                f_cadmednome.setText("");
                f_cadmednasc.setText("");
                f_cadmedcrm.setText("");
                f_cadmedend.setText("");
                f_cadmedemail.setText("");
                f_cadmedtel.setText("");
                f_cadmedcod.setText("");
                
                preencherTabela("SELECT * FROM cadmedicos ORDER BY nome_med");
                }
            }
        
    }//GEN-LAST:event_btn_cadsalvarActionPerformed

    private void btn_cadnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadnovoActionPerformed

        cont = 1;
        
        f_cadmednome.setEnabled(true);
        f_cadmednasc.setEnabled(true);
        f_cadmedcrm.setEnabled(true);
        f_cadmedend.setEnabled(true);
        f_cadmedemail.setEnabled(true);
        f_cadmedtel.setEnabled(true);
        f_cadmedpesquisa.setEnabled(false);
        jEspecializacao.setEnabled(true);
        btn_cadsalvar.setEnabled(true);
        btn_cadcancel.setEnabled(true);
        btn_cadedit.setEnabled(false);
        btn_cadexcluir.setEnabled(false);
        btn_cadpesquisa.setEnabled(false);
        f_cadmednome.setText("");
        f_cadmednasc.setText("");
        f_cadmedcrm.setText("");
        f_cadmedend.setText("");
        f_cadmedemail.setText("");
        f_cadmedtel.setText("");
        f_cadmedcod.setText("");
        f_cadmedpesquisa.setText("");
        
                
        f_cadmednome.requestFocus();
    }//GEN-LAST:event_btn_cadnovoActionPerformed

    private void btn_cadcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadcancelActionPerformed
        
        /*SistemaGUI voltamainsist = new SistemaGUI();
        voltamainsist.setVisible(true);
        dispose(); */
        
        f_cadmednome.setEnabled(!true);
        f_cadmednasc.setEnabled(!true);
        f_cadmedcrm.setEnabled(!true);
        f_cadmedend.setEnabled(!true);
        f_cadmedemail.setEnabled(!true);
        f_cadmedtel.setEnabled(!true);
        jEspecializacao.setEnabled(!true);
        f_cadmedpesquisa.setEnabled(true);
        btn_cadsalvar.setEnabled(!true);
        btn_cadnovo.setEnabled(true);
        btn_cadedit.setEnabled(false);
        btn_cadcancel.setEnabled(false);
        btn_cadexcluir.setEnabled(false);
        btn_cadpesquisa.setEnabled(true);
        
        f_cadmednome.setText("");
        f_cadmednasc.setText("");
        f_cadmedcrm.setText("");
        f_cadmedend.setText("");
        f_cadmedemail.setText("");
        f_cadmedtel.setText("");
        
        
    }//GEN-LAST:event_btn_cadcancelActionPerformed

    private void btn_cadpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadpesquisaActionPerformed
        
        meddto.setPesquisa(f_cadmedpesquisa.getText());
        
        MedicoDTO medicoDTO = meddao.pesquisaMed(meddto);
        f_cadmedcod.setText(String.valueOf(medicoDTO.getCodigo()));
        f_cadmednome.setText(medicoDTO.getNome());
        f_cadmednasc.setText(String.valueOf(medicoDTO.getNasc()));
        f_cadmedcrm.setText(String.valueOf(medicoDTO.getCrm()));
        f_cadmedend.setText(medicoDTO.getEndereco());
        f_cadmedemail.setText(medicoDTO.getEmail());
        f_cadmedtel.setText(medicoDTO.getTelefone());
        jEspecializacao.setSelectedItem(medicoDTO.getEspecializacao());
        
        preencherTabela("SELECT * FROM " + tabmed + " WHERE nome_med like '%" + meddto.getPesquisa()+"%'");
        
        
        
        
    }//GEN-LAST:event_btn_cadpesquisaActionPerformed

    private void btn_cadeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadeditActionPerformed

        cont = 2;
        f_cadmednome.setEnabled(true);
        f_cadmednasc.setEnabled(true);
        f_cadmedcrm.setEnabled(true);
        f_cadmedend.setEnabled(true);
        f_cadmedemail.setEnabled(true);
        f_cadmedtel.setEnabled(true);
        jEspecializacao.setEnabled(true);
        btn_cadsalvar.setEnabled(true);
        
        btn_cadedit.setEnabled(false);
        btn_cadnovo.setEnabled(false);
        btn_cadexcluir.setEnabled(false);
        btn_cadcancel.setEnabled(true);
        f_cadmednome.requestFocus();
    }//GEN-LAST:event_btn_cadeditActionPerformed

    private void btn_cadexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadexcluirActionPerformed
        
        int resp = 0;
        resp = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir esse registro?");
        if(resp == JOptionPane.YES_OPTION){
            meddto.setCodigo(Integer.parseInt(f_cadmedcod.getText()));
            meddao.excluir(meddto);
            
            f_cadmednome.setEnabled(false);
            f_cadmednasc.setEnabled(false);
            f_cadmedcrm.setEnabled(false);
            f_cadmedend.setEnabled(false);
            f_cadmedemail.setEnabled(false);
            f_cadmedtel.setEnabled(false);
            jEspecializacao.setEnabled(false);
            btn_cadsalvar.setEnabled(false);
            btn_cadnovo.setEnabled(true);
            btn_cadcancel.setEnabled(false);
            btn_cadedit.setEnabled(false);
            btn_cadexcluir.setEnabled(false);
            
            f_cadmednome.setText("");
            f_cadmednasc.setText("");
            f_cadmedcrm.setText("");
            f_cadmedend.setText("");
            f_cadmedemail.setText("");
            f_cadmedtel.setText("");
            f_cadmedcod.setText("");
            f_cadmedpesquisa.setText("");
            preencherTabela("SELECT * FROM cadmedicos ORDER BY nome_med");
        }
        
    }//GEN-LAST:event_btn_cadexcluirActionPerformed

    private void table_cadmedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_cadmedMouseClicked
        
        String nome_med = ""+table_cadmed.getValueAt(table_cadmed.getSelectedRow(), 1);
        conn.conect();
        String query = "SELECT * FROM " + tabmed + " WHERE nome_med = '" + nome_med + "'";
        conn.executaSql(query);
        try {
            conn.rs.first();
            f_cadmedcod.setText(String.valueOf(conn.rs.getInt("cod_med")));
            f_cadmednome.setText(conn.rs.getString("nome_med"));
            f_cadmednasc.setText(String.valueOf(conn.rs.getInt("nasc_med")));
            f_cadmedcrm.setText(String.valueOf(conn.rs.getInt("crm_med")));
            f_cadmedend.setText(conn.rs.getString("end_med"));
            f_cadmedemail.setText(conn.rs.getString("email_med"));
            f_cadmedtel.setText(conn.rs.getString("tel_med"));
            jEspecializacao.setSelectedItem(conn.rs.getString("espec_med"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar o registro: " + ex);
        }
        btn_cadedit.setEnabled(true);
        btn_cadexcluir.setEnabled(true);
        
        
        
    }//GEN-LAST:event_table_cadmedMouseClicked

    private void f_cadmedpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_cadmedpesquisaActionPerformed
        
    }//GEN-LAST:event_f_cadmedpesquisaActionPerformed

    public void preencherTabela(String sql){
        
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Nascimento", "CRM", "Endereço", "E-mail", "Telefone", "Especialização"};
        conn.conect();
        conn.executaSql(sql);
        
        try {
            conn.rs.first();
            do {                
                dados.add(new Object[]{conn.rs.getInt("cod_med"), conn.rs.getString("nome_med"), conn.rs.getInt("nasc_med"), 
                    conn.rs.getInt("crm_med"), conn.rs.getString("end_med"), conn.rs.getString("email_med"), 
                    conn.rs.getString("tel_med"), conn.rs.getString("espec_med")});
                                    
            } while (conn.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Insira outro nome para preencher a tabela!");
        }
        
        TabelaDTO tabdto = new TabelaDTO(dados, colunas);
                
        table_cadmed.setModel(tabdto);
        table_cadmed.getColumnModel().getColumn(0).setPreferredWidth(23);
        table_cadmed.getColumnModel().getColumn(0).setResizable(false);
        table_cadmed.getColumnModel().getColumn(1).setPreferredWidth(120);
        table_cadmed.getColumnModel().getColumn(1).setResizable(false);
        table_cadmed.getColumnModel().getColumn(2).setPreferredWidth(75);
        table_cadmed.getColumnModel().getColumn(2).setResizable(false);
        table_cadmed.getColumnModel().getColumn(3).setPreferredWidth(75);
        table_cadmed.getColumnModel().getColumn(3).setResizable(false);
        table_cadmed.getColumnModel().getColumn(4).setPreferredWidth(120);
        table_cadmed.getColumnModel().getColumn(4).setResizable(false);
        table_cadmed.getColumnModel().getColumn(5).setPreferredWidth(160);
        table_cadmed.getColumnModel().getColumn(5).setResizable(false);
        table_cadmed.getColumnModel().getColumn(6).setPreferredWidth(90);
        table_cadmed.getColumnModel().getColumn(6).setResizable(false);
        table_cadmed.getColumnModel().getColumn(7).setPreferredWidth(90);
        table_cadmed.getColumnModel().getColumn(7).setResizable(false);
        
        table_cadmed.getTableHeader().setReorderingAllowed(false);
        table_cadmed.setAutoResizeMode(table_cadmed.AUTO_RESIZE_OFF);
        table_cadmed.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedicoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedicoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedicoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedicoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMedicoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadcancel;
    private javax.swing.JButton btn_cadedit;
    private javax.swing.JButton btn_cadexcluir;
    private javax.swing.JButton btn_cadnovo;
    private javax.swing.JButton btn_cadpesquisa;
    private javax.swing.JButton btn_cadsalvar;
    private javax.swing.JTextField f_cadmedcod;
    private javax.swing.JTextField f_cadmedcrm;
    private javax.swing.JTextField f_cadmedemail;
    private javax.swing.JTextField f_cadmedend;
    private javax.swing.JTextField f_cadmednasc;
    private javax.swing.JTextField f_cadmednome;
    private javax.swing.JTextField f_cadmedpesquisa;
    private javax.swing.JTextField f_cadmedtel;
    private javax.swing.JPanel fundo_cadmed;
    private javax.swing.JComboBox<String> jEspecializacao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_cadmed;
    private javax.swing.JLabel txt_cadmedicos;
    // End of variables declaration//GEN-END:variables
}
