/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author QUARTZO
 */
public class LoginGUI extends javax.swing.JFrame {

    String tabela = "cadusuarios";
    Conexao conn = new Conexao();
    
    
    public LoginGUI() {
        initComponents();
        
        conn.conect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_logo = new javax.swing.JLabel();
        txt_logo2 = new javax.swing.JLabel();
        txt_logo = new javax.swing.JLabel();
        txt_senha = new javax.swing.JLabel();
        txt_login = new javax.swing.JLabel();
        f_login = new javax.swing.JTextField();
        btn_acessar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        f_senha = new javax.swing.JPasswordField();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        img_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_logo.png"))); // NOI18N
        getContentPane().add(img_logo);
        img_logo.setBounds(10, 90, 80, 70);

        txt_logo2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txt_logo2.setForeground(new java.awt.Color(255, 51, 51));
        txt_logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_logo2.setText("Sistema médico de saúde");
        getContentPane().add(txt_logo2);
        txt_logo2.setBounds(80, 120, 220, 40);

        txt_logo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        txt_logo.setForeground(new java.awt.Color(255, 51, 51));
        txt_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_logo.setText("SYSMED");
        getContentPane().add(txt_logo);
        txt_logo.setBounds(80, 90, 160, 40);

        txt_senha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_senha.setForeground(new java.awt.Color(51, 51, 51));
        txt_senha.setText("SENHA");
        getContentPane().add(txt_senha);
        txt_senha.setBounds(420, 130, 50, 20);

        txt_login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_login.setForeground(new java.awt.Color(51, 51, 51));
        txt_login.setText("LOGIN");
        getContentPane().add(txt_login);
        txt_login.setBounds(420, 70, 50, 20);
        getContentPane().add(f_login);
        f_login.setBounds(420, 90, 190, 30);

        btn_acessar.setText("ACESSAR!");
        btn_acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acessarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_acessar);
        btn_acessar.setBounds(420, 200, 100, 30);

        btn_sair.setText("SAIR!");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sair);
        btn_sair.setBounds(530, 200, 80, 30);
        getContentPane().add(f_senha);
        f_senha.setBounds(420, 150, 190, 30);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/blurred-image-1.jpg"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 660, 300);

        setSize(new java.awt.Dimension(660, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acessarActionPerformed
        
        try {
            String query = "SELECT * FROM " + tabela + " WHERE usuario_user = '" +f_login.getText()+"'";
            conn.executaSql(query);
            conn.rs.first();
            if(conn.rs.getString("senha_user").equals(f_senha.getText())){
                SistemaGUI telasistema = new SistemaGUI(f_login.getText());
                telasistema.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Usuário ou senha inválidos.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao executar a validação! Dados: "+e.getMessage());
        }
     
    }//GEN-LAST:event_btn_acessarActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acessar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JTextField f_login;
    private javax.swing.JPasswordField f_senha;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel img_logo;
    private javax.swing.JLabel txt_login;
    private javax.swing.JLabel txt_logo;
    private javax.swing.JLabel txt_logo2;
    private javax.swing.JLabel txt_senha;
    // End of variables declaration//GEN-END:variables
}
