/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author QUARTZO
 */
public class SistemaGUI extends javax.swing.JFrame {

    Conexao conn = new Conexao();
    FormMedicoGUI formmedico = new FormMedicoGUI();
    FormUsuariosGUI formusuario = new FormUsuariosGUI();
    String tabela = "cadusuarios";
    
    public SistemaGUI(String usuario) {
        initComponents();
        marcUser.setText(usuario);
        conn.conect();
    }

    SistemaGUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBemvindo = new javax.swing.JInternalFrame();
        btn_exitpanel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_labelcad = new javax.swing.JLabel();
        btn_cadmed = new javax.swing.JButton();
        btn_cadenf = new javax.swing.JButton();
        btn_cadpac = new javax.swing.JButton();
        txt_agenda = new javax.swing.JLabel();
        btn_agenda = new javax.swing.JButton();
        fdimgpanel = new javax.swing.JLabel();
        txt_sistemagerenc = new javax.swing.JLabel();
        marcUser = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menucadastro = new javax.swing.JMenu();
        cadmedicos = new javax.swing.JMenuItem();
        cadpacientes = new javax.swing.JMenuItem();
        cadenfermeiros = new javax.swing.JMenuItem();
        cadusuarios = new javax.swing.JMenuItem();
        menurelatorios = new javax.swing.JMenu();
        menuagenda = new javax.swing.JMenu();
        menuferramentas = new javax.swing.JMenu();
        telabemvindos = new javax.swing.JMenuItem();
        menusair = new javax.swing.JMenu();
        menuencerra = new javax.swing.JMenuItem();
        menudesconect = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jBemvindo.setTitle("Bem vindo");
        jBemvindo.setVisible(true);
        jBemvindo.getContentPane().setLayout(null);

        btn_exitpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exit.png"))); // NOI18N
        btn_exitpanel.setToolTipText("Fechar Tela");
        btn_exitpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitpanelActionPerformed(evt);
            }
        });
        jBemvindo.getContentPane().add(btn_exitpanel);
        btn_exitpanel.setBounds(730, 10, 30, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        txt_labelcad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_labelcad.setForeground(new java.awt.Color(153, 255, 255));
        txt_labelcad.setText("Cadastros:");
        jPanel1.add(txt_labelcad);
        txt_labelcad.setBounds(30, 20, 70, 20);

        btn_cadmed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CadMedicos.png"))); // NOI18N
        btn_cadmed.setToolTipText("Médicos");
        btn_cadmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadmedActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadmed);
        btn_cadmed.setBounds(30, 50, 73, 50);

        btn_cadenf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-infermeira.png"))); // NOI18N
        btn_cadenf.setToolTipText("Enfermeiros");
        jPanel1.add(btn_cadenf);
        btn_cadenf.setBounds(120, 50, 70, 50);

        btn_cadpac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadPacientes.png"))); // NOI18N
        btn_cadpac.setToolTipText("Pacientes");
        jPanel1.add(btn_cadpac);
        btn_cadpac.setBounds(210, 50, 67, 50);

        txt_agenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_agenda.setForeground(new java.awt.Color(153, 255, 255));
        txt_agenda.setText("Agenda:");
        jPanel1.add(txt_agenda);
        txt_agenda.setBounds(30, 120, 60, 20);

        btn_agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Agenda.png"))); // NOI18N
        btn_agenda.setToolTipText("Agendamentos");
        btn_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda);
        btn_agenda.setBounds(30, 150, 65, 50);

        fdimgpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/06.jpg"))); // NOI18N
        jPanel1.add(fdimgpanel);
        fdimgpanel.setBounds(0, 0, 790, 300);

        jBemvindo.getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 50, 790, 310);

        txt_sistemagerenc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_sistemagerenc.setText("SISTEMA DE GERENCIAMENTO DE:");
        jBemvindo.getContentPane().add(txt_sistemagerenc);
        txt_sistemagerenc.setBounds(20, 20, 230, 20);

        getContentPane().add(jBemvindo);
        jBemvindo.setBounds(0, 60, 780, 380);

        marcUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        marcUser.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(marcUser);
        marcUser.setBounds(90, 20, 130, 20);

        txt_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(0, 153, 0));
        txt_usuario.setText("Bem vindo,");
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(10, 20, 90, 20);

        menucadastro.setText("Cadastros");

        cadmedicos.setText("Cadastro de médicos");
        cadmedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadmedicosActionPerformed(evt);
            }
        });
        menucadastro.add(cadmedicos);

        cadpacientes.setText("Cadastro de pacientes");
        cadpacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadpacientesActionPerformed(evt);
            }
        });
        menucadastro.add(cadpacientes);

        cadenfermeiros.setText("Cadastro de enfermeiros");
        menucadastro.add(cadenfermeiros);

        cadusuarios.setText("Cadastro de usuários");
        cadusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadusuariosActionPerformed(evt);
            }
        });
        menucadastro.add(cadusuarios);

        menu.add(menucadastro);

        menurelatorios.setText("Relatórios");
        menu.add(menurelatorios);

        menuagenda.setText("Agendamentos");
        menu.add(menuagenda);

        menuferramentas.setText("Ferramentas");

        telabemvindos.setText("Tela Bem-vindos");
        telabemvindos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telabemvindosActionPerformed(evt);
            }
        });
        menuferramentas.add(telabemvindos);

        menu.add(menuferramentas);

        menusair.setText("Sair");

        menuencerra.setText("Encerrar");
        menuencerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuencerraActionPerformed(evt);
            }
        });
        menusair.add(menuencerra);

        menudesconect.setText("Desconectar");
        menudesconect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudesconectActionPerformed(evt);
            }
        });
        menusair.add(menudesconect);

        menu.add(menusair);

        setJMenuBar(menu);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadpacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadpacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadpacientesActionPerformed

    private void btn_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agendaActionPerformed

    private void btn_exitpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitpanelActionPerformed
        jBemvindo.dispose();
    }//GEN-LAST:event_btn_exitpanelActionPerformed

    private void menuencerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuencerraActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuencerraActionPerformed

    private void telabemvindosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telabemvindosActionPerformed
        jBemvindo.setVisible(true);
    }//GEN-LAST:event_telabemvindosActionPerformed

    private void menudesconectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudesconectActionPerformed
        
        LoginGUI telalogin = new LoginGUI();
        telalogin.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_menudesconectActionPerformed

    private void cadmedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadmedicosActionPerformed

        try {
            String query = "SELECT * FROM " + tabela + " WHERE usuario_user = '" +marcUser.getText()+"'";
            conn.executaSql(query);
            conn.rs.first();
            if(conn.rs.getString("acesso_user").equals("Administrador") || conn.rs.getString("acesso_user").equals("Médico")){
                if(formmedico == null){
                    formmedico = new FormMedicoGUI();
                    formmedico.setVisible(true);
                    formmedico.setResizable(false);
                }else{
                    formmedico.setVisible(true);
                    formmedico.setResizable(false);
                }

                //FormMedicoGUI formmedico = new FormMedicoGUI();
                //formmedico.setVisible(true);
                //dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Acesso negado para este usuário.\nContate o administrador!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "[WAR]Acesso negado para este usuário.\nContate o administrador!");
        }    
    }//GEN-LAST:event_cadmedicosActionPerformed

    private void btn_cadmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadmedActionPerformed
        try {
            String query = "SELECT * FROM " + tabela + " WHERE usuario_user = '" +marcUser.getText()+"'";
            conn.executaSql(query);
            conn.rs.first();
            if(conn.rs.getString("acesso_user").equals("Administrador") || conn.rs.getString("acesso_user").equals("Médico")){
                if(formmedico == null){
                    formmedico = new FormMedicoGUI();
                    formmedico.setVisible(true);
                    formmedico.setResizable(false);
                }else{
                    formmedico.setVisible(true);
                    formmedico.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Acesso negado para este usuário.\nContate o administrador!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "[WAR]Acesso negado para este usuário.\nContate o administrador!");
        }
    }//GEN-LAST:event_btn_cadmedActionPerformed

    private void cadusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadusuariosActionPerformed
        
        try {
            String query = "SELECT * FROM " + tabela + " WHERE usuario_user = '" +marcUser.getText()+"'";
            conn.executaSql(query);
            conn.rs.first();
            if(conn.rs.getString("acesso_user").equals("Administrador")){
                if(formusuario == null){
                    formusuario = new FormUsuariosGUI();
                    formusuario.setVisible(true);
                    formusuario.setResizable(false);
                }else{
                    formusuario.setVisible(true);
                    formusuario.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Acesso negado para este usuário.\nContate o administrador!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "[WAR]Acesso negado para este usuário.\nContate o administrador!");
        }
    }//GEN-LAST:event_cadusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agenda;
    private javax.swing.JButton btn_cadenf;
    private javax.swing.JButton btn_cadmed;
    private javax.swing.JButton btn_cadpac;
    private javax.swing.JButton btn_exitpanel;
    private javax.swing.JMenuItem cadenfermeiros;
    private javax.swing.JMenuItem cadmedicos;
    private javax.swing.JMenuItem cadpacientes;
    private javax.swing.JMenuItem cadusuarios;
    private javax.swing.JLabel fdimgpanel;
    private javax.swing.JInternalFrame jBemvindo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marcUser;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuagenda;
    private javax.swing.JMenu menucadastro;
    private javax.swing.JMenuItem menudesconect;
    private javax.swing.JMenuItem menuencerra;
    private javax.swing.JMenu menuferramentas;
    private javax.swing.JMenu menurelatorios;
    private javax.swing.JMenu menusair;
    private javax.swing.JMenuItem telabemvindos;
    private javax.swing.JLabel txt_agenda;
    private javax.swing.JLabel txt_labelcad;
    private javax.swing.JLabel txt_sistemagerenc;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
